application: eventplanners
version: 1
runtime: python27
api_version: 1
threadsafe: no  #always safe to start out with no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /event\.css
  static_files: event.css
  upload: event\.css

- url: /event\.js
  static_files: event.js
  upload: event\.js

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
